use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A single text chunk from the SRD corpus used for RAG retrieval.
/// `text_en` is always English per bilingual discipline (embedding quality is
/// higher on English; Russian narration is generated by the LLM from EN context).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SrdChunk {
    pub id: Uuid,
    pub source_key: String,
    pub text_en: String,
    /// Embedding vector stored as f32 LE bytes. None before embedding is run.
    #[serde(skip)]
    pub embedding: Option<Vec<f32>>,
}

impl SrdChunk {
    pub fn new(source_key: impl Into<String>, text_en: impl Into<String>) -> Self {
        Self {
            id: Uuid::new_v4(),
            source_key: source_key.into(),
            text_en: text_en.into(),
            embedding: None,
        }
    }
}

/// Raw YAML schema for a single chunk entry.
#[derive(Debug, Deserialize)]
struct YamlChunkEntry {
    key: String,
    text: String,
}

/// Load `SrdChunk`s from a YAML string.
/// YAML format:
/// ```yaml
/// chunks:
///   - key: magic_missile
///     text: "Magic Missile. 1st-level evocation. ..."
///   - key: fireball
///     text: "Fireball. 3rd-level evocation. ..."
/// ```
pub fn load_chunks_from_yaml(yaml: &str) -> Result<Vec<SrdChunk>, serde_yaml::Error> {
    #[derive(Deserialize)]
    struct YamlFile {
        chunks: Vec<YamlChunkEntry>,
    }
    let file: YamlFile = serde_yaml::from_str(yaml)?;
    Ok(file
        .chunks
        .into_iter()
        .map(|e| SrdChunk::new(e.key, e.text))
        .collect())
}
