[package]
name = "app-domain"
version = "0.12.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1", features = ["v4", "serde"] }
rand = { version = "0.10", features = ["sys_rng"] }
serde_yaml = "0.9"

[dev-dependencies]
serde_json = { workspace = true }
