name: quality

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        run: |
          bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

  typos:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: error
          scandir: ./scripts

  psscriptanalyzer:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          $results = Invoke-ScriptAnalyzer -Path scripts -Recurse -Severity Error
          if ($results) {
            $results | Format-Table -AutoSize
            exit 1
          }

  markdownlint:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"

  yamllint:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: .yamllint.yml

  editorconfig:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
